-- DEMO SEED (cleanable). Realistic Thai-market companies, jobs and events.
-- Image URLs use public CDNs (Clearbit logos, Picsum photos) to simulate
-- uploaded media; the real upload feature writes to Storage buckets.
-- Teardown: delete from events/jobs/companies where created_by is null;

/* Companies */
insert into public.companies (slug, name, tagline, about, industry, size, location, website, logo_url, founded, hiring)
values
  ('agoda','Agoda','Bridging the world through travel, built in Bangkok.','Agoda is one of the world''s largest online travel platforms, headquartered in Bangkok. Our engineering and data teams build at massive scale for hundreds of millions of travelers.','Software','5,000+','Bangkok','agoda.com','https://logo.clearbit.com/agoda.com',2005,true),
  ('lineman-wongnai','LINE MAN Wongnai','Thailand''s everyday super-app for food and services.','LINE MAN Wongnai powers food delivery, reviews and merchant services for tens of millions of Thais. A fast-scaling local tech leader.','E-commerce','1,001-5,000','Bangkok','lmwn.com','https://logo.clearbit.com/lmwn.com',2020,true),
  ('scb-techx','SCB TechX','Building Thailand''s digital banking backbone.','SCB TechX is the technology arm of SCB, one of Thailand''s largest banks, shipping cloud-native financial products used across the kingdom.','Fintech','501-1,000','Bangkok','scbtechx.io','https://logo.clearbit.com/scbtechx.io',2021,true),
  ('bitkub','Bitkub','Thailand''s leading digital asset exchange.','Bitkub is the most-used crypto exchange in Thailand, bringing decentralized technology to the region.','Fintech','501-1,000','Bangkok','bitkub.com','https://logo.clearbit.com/bitkub.com',2018,true),
  ('shopee','Shopee','E-commerce across Southeast Asia.','Shopee, part of Sea Group, builds commerce experiences for the whole region from its Bangkok teams.','E-commerce','5,000+','Bangkok','shopee.co.th','https://logo.clearbit.com/shopee.com',2015,true),
  ('kbtg','KBTG','Kasikorn Business-Technology Group.','KBTG is the technology powerhouse behind KBank, recognised for AI research and one of Thailand''s top engineering cultures.','Data & AI','1,001-5,000','Bangkok','kbtg.tech','https://logo.clearbit.com/kbtg.tech',2016,true),
  ('sertis','Sertis','AI and data consulting for enterprise Thailand.','Sertis is a leading AI and big-data company helping the region''s largest enterprises become data-driven.','Data & AI','201-500','Bangkok','sertiscorp.com','https://logo.clearbit.com/sertiscorp.com',2014,true),
  ('lazada','Lazada','Shopping, redefined for Thailand.','Lazada is a flagship Southeast Asian e-commerce platform, part of Alibaba Group, with a large Bangkok base.','E-commerce','1,001-5,000','Bangkok','lazada.co.th','https://logo.clearbit.com/lazada.com',2012,true),
  ('truemoney','TrueMoney','Financial inclusion across the region.','TrueMoney (Ascend Money) is a leading fintech wallet serving millions across Southeast Asia.','Fintech','1,001-5,000','Bangkok','truemoney.com','https://logo.clearbit.com/truemoney.com',2013,true),
  ('amity','Amity','Social and conversational software, globally.','Amity is a Bangkok-born SaaS company building social and AI products used by enterprises worldwide.','Software','201-500','Bangkok','amity.co','https://logo.clearbit.com/amity.co',2012,true);

/* Jobs (company referenced by slug) */
insert into public.jobs (slug, company_id, title, type, work_mode, location, industry, salary_min, salary_max, salary_period, description, responsibilities, requirements, skills, featured, posted_at)
values
  ('frontend-engineer-intern-agoda',(select id from public.companies where slug='agoda'),'Frontend Engineer Intern','Internship','Hybrid','Bangkok','Software',25000,35000,'mo','Join Agoda''s web platform team building features used by millions of travelers. Work with senior engineers on our React/TypeScript codebase.','{"Build and ship UI features in React + TypeScript","Collaborate with designers and product managers","Write tests and join code reviews"}','{"Pursuing a CS or related degree","Familiar with JavaScript and React","Available 4+ months, based near Bangkok"}','{"React","TypeScript","CSS","Git"}',true, now() - interval '2 days'),
  ('data-engineering-intern-agoda',(select id from public.companies where slug='agoda'),'Data Engineering Intern','Internship','Hybrid','Bangkok','Data & AI',25000,35000,'mo','Work on data pipelines moving billions of events for Agoda''s analytics and ML.','{"Build and maintain ETL pipelines","Work with Spark and streaming systems","Improve data quality"}','{"CS/Data student","Python and SQL","Curious about distributed systems"}','{"Python","SQL","Spark","Airflow"}',true, now() - interval '1 day'),
  ('backend-engineer-lineman-wongnai',(select id from public.companies where slug='lineman-wongnai'),'Backend Engineer','Full-time','Hybrid','Bangkok','E-commerce',60000,95000,'mo','Build the services that power food delivery for millions of Thais with Kotlin, Go and a high-scale microservices architecture.','{"Design and operate high-throughput services","Improve reliability and latency","Mentor junior engineers"}','{"2+ years backend experience","Strong systems fundamentals","Kotlin, Go or Java"}','{"Kotlin","Go","Kubernetes","PostgreSQL"}',true, now() - interval '4 days'),
  ('data-analyst-new-grad-scb-techx',(select id from public.companies where slug='scb-techx'),'Data Analyst (New Grad)','New grad','Hybrid','Bangkok','Fintech',35000,50000,'mo','Kickstart your career analysing banking data that informs product decisions across SCB''s digital platforms.','{"Build dashboards and reports in SQL + BI tools","Partner with product teams on metrics","Translate data into recommendations"}','{"Bachelor''s in a quantitative field","Strong SQL and spreadsheets","Good written English and Thai"}','{"SQL","Python","Tableau","Statistics"}',true, now() - interval '1 day'),
  ('product-management-intern-bitkub',(select id from public.companies where slug='bitkub'),'Product Management Intern','Internship','On-site','Bangkok','Fintech',18000,22000,'mo','Support the product team building Thailand''s most popular crypto exchange. Great exposure to fintech and Web3.','{"Help write specs and user stories","Run user research","Track feature metrics"}','{"Penultimate or final-year student","Curious about crypto and product","Strong communication"}','{"Product sense","Figma","Analytics","Communication"}',false, now() - interval '6 days'),
  ('data-scientist-shopee',(select id from public.companies where slug='shopee'),'Data Scientist','Full-time','On-site','Bangkok','E-commerce',70000,110000,'mo','Work on recommendation and pricing models for Shopee across Southeast Asia.','{"Develop and deploy ML models","Run A/B experiments at scale","Collaborate with engineering on serving"}','{"MSc or equivalent in ML/Stats","Strong Python and ML fundamentals","Experience with large datasets"}','{"Python","Machine Learning","SQL","Spark"}',false, now() - interval '3 days'),
  ('ml-engineer-intern-kbtg',(select id from public.companies where slug='kbtg'),'Machine Learning Engineer Intern','Internship','Hybrid','Bangkok','Data & AI',22000,30000,'mo','Join KBTG''s AI research lab and ship ML features into banking products used across Thailand.','{"Prototype models for NLP and document AI","Help productionize research","Present findings"}','{"Pursuing CS/Data degree","Python and PyTorch or TensorFlow","Solid math foundations"}','{"Python","PyTorch","NLP","Docker"}',true, now() - interval '5 days'),
  ('software-engineer-new-grad-kbtg',(select id from public.companies where slug='kbtg'),'Software Engineer (New Grad)','New grad','Hybrid','Bangkok','Fintech',45000,65000,'mo','Start your engineering career at one of Thailand''s strongest tech cultures.','{"Build banking features end-to-end","Learn from senior engineers","Write clean, tested code"}','{"Fresh CS/Engineering graduate","Solid programming fundamentals","Eager to learn"}','{"Java","Spring","SQL","Git"}',false, now() - interval '2 days'),
  ('junior-data-scientist-sertis',(select id from public.companies where slug='sertis'),'Junior Data Scientist','New grad','Hybrid','Bangkok','Data & AI',40000,60000,'mo','Solve real enterprise problems with data across retail, energy and finance clients.','{"Build models and pipelines for clients","Communicate insights to stakeholders","Work in cross-functional teams"}','{"Bachelor''s/Master''s in quantitative field","Python and SQL","Comfortable presenting"}','{"Python","SQL","Machine Learning","Communication"}',false, now() - interval '8 days'),
  ('operations-associate-new-grad-lazada',(select id from public.companies where slug='lazada'),'Operations Associate (New Grad)','New grad','On-site','Bangkok','E-commerce',28000,38000,'mo','Drive efficiency across Lazada''s marketplace and logistics operations.','{"Analyze and improve operational metrics","Coordinate across teams and sellers","Own process improvements"}','{"Fresh graduate, any discipline","Strong Excel and analytics","Fluent Thai and good English"}','{"Excel","Analytics","Operations","Communication"}',false, now() - interval '9 days'),
  ('growth-marketing-intern-truemoney',(select id from public.companies where slug='truemoney'),'Growth Marketing Intern','Internship','Hybrid','Bangkok','Marketing',15000,20000,'mo','Help grow TrueMoney''s user base with data-driven marketing campaigns.','{"Support performance marketing campaigns","Analyze campaign results","Create content for social"}','{"Marketing or business student","Analytical and creative","Social media savvy"}','{"Marketing","Analytics","Content","Social Media"}',false, now() - interval '12 days'),
  ('fullstack-engineer-amity',(select id from public.companies where slug='amity'),'Full-Stack Engineer','Full-time','Remote','Remote (Thailand)','Software',55000,90000,'mo','Build SaaS products used by enterprises worldwide, from API to UI.','{"Ship features across the stack (Node + React)","Design APIs and data models","Care about quality and DX"}','{"2+ years full-stack experience","TypeScript, Node, React","Comfortable remote"}','{"TypeScript","Node.js","React","PostgreSQL"}',true, now() - interval '3 days'),
  ('product-design-intern-lazada',(select id from public.companies where slug='lazada'),'Product Design Intern','Internship','Hybrid','Bangkok','Design',18000,25000,'mo','Design delightful consumer experiences for Lazada''s shopping products.','{"Create wireframes and hi-fi designs in Figma","Contribute to the design system","Run usability tests"}','{"Design student with a portfolio","Figma proficiency","Eye for interaction"}','{"Figma","UI Design","Prototyping","User Research"}',false, now() - interval '7 days'),
  ('devops-engineer-scb-techx',(select id from public.companies where slug='scb-techx'),'DevOps Engineer','Full-time','Remote','Remote (Thailand)','Fintech',80000,120000,'mo','Keep banking infrastructure reliable and secure.','{"Operate cloud infra and CI/CD","Improve observability and on-call","Automate everything"}','{"3+ years DevOps/SRE","AWS or GCP, Kubernetes, Terraform","Security-minded"}','{"AWS","Kubernetes","Terraform","CI/CD"}',false, now() - interval '10 days'),
  ('backend-intern-bitkub',(select id from public.companies where slug='bitkub'),'Backend Engineer Intern','Internship','On-site','Bangkok','Fintech',20000,28000,'mo','Build and operate services behind Thailand''s leading crypto exchange.','{"Implement backend endpoints","Write tests and docs","Learn high-availability systems"}','{"CS student","Java, Go or Node","Interested in fintech"}','{"Go","PostgreSQL","Redis","Docker"}',false, now() - interval '5 days');

/* Events */
insert into public.events (slug, title, host, kind, mode, location, image_url, starts_at, duration_mins, description, company_id)
values
  ('chula-tech-career-fair-2026','Chula Tech Career Fair 2026','Chulalongkorn University','Career fair','On-site','Chamchuri Square, Bangkok','https://picsum.photos/seed/chulafair/800/450', now() + interval '6 days', 360,'Meet 40+ top tech employers hiring interns and new grads. Bring your resume and your questions.', null),
  ('inside-agoda-engineering','Inside Agoda Engineering','Agoda','Info session','Hybrid','Agoda HQ + Online','https://picsum.photos/seed/agodaeng/800/450', now() + interval '3 days', 90,'Engineers share what it''s like to build at scale, followed by a live Q&A and internship walkthrough.', (select id from public.companies where slug='agoda')),
  ('resume-workshop-for-new-grads','Resume Workshop for New Grads','Spotlights','Workshop','Remote','Online','https://picsum.photos/seed/resumews/800/450', now() + interval '2 days', 60,'A hands-on session on building a standout resume for the Thai tech market. Templates included.', null),
  ('kbtg-ai-night','KBTG AI Night','KBTG','Networking','On-site','KBTG Campus, Bangkok','https://picsum.photos/seed/kbtgai/800/450', now() + interval '14 days', 180,'Talks from KBTG''s AI lab plus networking with researchers and recruiters. Refreshments provided.', (select id from public.companies where slug='kbtg')),
  ('northern-thailand-startup-fair','Northern Thailand Startup Fair','Chiang Mai University','Career fair','On-site','CMU Convention Hall, Chiang Mai','https://picsum.photos/seed/cmufair/800/450', now() + interval '20 days', 300,'Connect with startups and scale-ups hiring across the North. Roles in software, data and operations.', null),
  ('breaking-into-fintech-panel','Breaking Into Fintech','Spotlights','Networking','Remote','Online','https://picsum.photos/seed/fintechpanel/800/450', now() + interval '9 days', 75,'A panel with engineers and PMs from SCB TechX, Bitkub and Opn on starting a fintech career.', null);
