-- Replace the demo seed with US big-tech companies, jobs (USD) and US events.
-- Cleanable: all rows have created_by = null. Deleting jobs/events cascades
-- demo applications/saved/rsvps; re-run seed-users.mjs to recreate activity.

delete from public.events where created_by is null;
delete from public.jobs where created_by is null;
delete from public.companies where created_by is null;

insert into public.companies (slug, name, tagline, about, industry, size, location, website, logo_url, founded, hiring) values
  ('google','Google','Organize the world''s information.','Google builds products that help billions of people, from Search and Maps to Android and Cloud. Engineering and research at planetary scale.','Software','10,000+','Mountain View, CA','google.com','https://www.google.com/s2/favicons?domain=google.com&sz=128',1998,true),
  ('apple','Apple','Think different.','Apple designs the iPhone, Mac, and the software and silicon that power them, with a relentless focus on craft and privacy.','Software','10,000+','Cupertino, CA','apple.com','https://www.google.com/s2/favicons?domain=apple.com&sz=128',1976,true),
  ('microsoft','Microsoft','Empower every person and organization.','Microsoft builds Azure, Windows, Office and developer tools used by individuals and enterprises worldwide.','Software','10,000+','Redmond, WA','microsoft.com','https://www.google.com/s2/favicons?domain=microsoft.com&sz=128',1975,true),
  ('amazon','Amazon','Earth''s most customer-centric company.','Amazon spans e-commerce, AWS cloud, devices and logistics, operating at massive global scale.','E-commerce','10,000+','Seattle, WA','amazon.com','https://www.google.com/s2/favicons?domain=amazon.com&sz=128',1994,true),
  ('meta','Meta','Building the future of connection.','Meta builds Facebook, Instagram, WhatsApp and reality-lab hardware connecting billions of people.','Software','10,000+','Menlo Park, CA','meta.com','https://www.google.com/s2/favicons?domain=meta.com&sz=128',2004,true),
  ('netflix','Netflix','Entertainment, unlimited.','Netflix streams series and films to hundreds of millions of members and builds the technology behind it.','Software','5,000+','Los Gatos, CA','netflix.com','https://www.google.com/s2/favicons?domain=netflix.com&sz=128',1997,true),
  ('nvidia','NVIDIA','The engine of modern AI.','NVIDIA builds the GPUs and software platforms powering AI, graphics and accelerated computing.','Data & AI','10,000+','Santa Clara, CA','nvidia.com','https://www.google.com/s2/favicons?domain=nvidia.com&sz=128',1993,true),
  ('stripe','Stripe','Economic infrastructure for the internet.','Stripe builds payments and financial tooling used by millions of businesses, from startups to enterprises.','Fintech','5,000+','San Francisco, CA','stripe.com','https://www.google.com/s2/favicons?domain=stripe.com&sz=128',2010,true),
  ('airbnb','Airbnb','Belong anywhere.','Airbnb is a community marketplace for stays and experiences in thousands of cities worldwide.','Software','5,000+','San Francisco, CA','airbnb.com','https://www.google.com/s2/favicons?domain=airbnb.com&sz=128',2008,true),
  ('openai','OpenAI','Ensuring AGI benefits all of humanity.','OpenAI is an AI research and deployment company building safe, broadly beneficial AI, including ChatGPT.','Data & AI','1,001-5,000','San Francisco, CA','openai.com','https://www.google.com/s2/favicons?domain=openai.com&sz=128',2015,true),
  ('tesla','Tesla','Accelerating the world to sustainable energy.','Tesla builds electric vehicles, batteries and solar, plus the software and autonomy behind them.','Energy','10,000+','Austin, TX','tesla.com','https://www.google.com/s2/favicons?domain=tesla.com&sz=128',2003,true),
  ('salesforce','Salesforce','The customer company.','Salesforce builds the leading CRM and a broad cloud platform for sales, service and analytics.','Software','10,000+','San Francisco, CA','salesforce.com','https://www.google.com/s2/favicons?domain=salesforce.com&sz=128',1999,true);

insert into public.jobs (slug, company_id, title, type, work_mode, location, industry, salary_min, salary_max, salary_period, description, responsibilities, requirements, skills, featured, posted_at) values
  ('software-engineer-intern-google',(select id from public.companies where slug='google'),'Software Engineer Intern','Internship','Hybrid','Mountain View, CA','Software',9000,11000,'mo','Spend the summer building features used by billions, mentored by senior Google engineers.','{"Build and ship features in a large codebase","Write tests and participate in code reviews","Collaborate with your team and mentor"}','{"Pursuing a CS or related degree","Solid data structures and algorithms","Experience in one of: Java, C++, Python, Go"}','{"Algorithms","Python","C++","Git"}',true, now() - interval '2 days'),
  ('new-grad-swe-google',(select id from public.companies where slug='google'),'Software Engineer, New Grad','New grad','On-site','Mountain View, CA','Software',130000,180000,'yr','Start your engineering career at Google working on products at planetary scale.','{"Design, build and ship production systems","Collaborate across teams","Grow with mentorship and code review"}','{"BS/MS in CS or equivalent","Strong fundamentals","Internship or project experience"}','{"Java","Distributed Systems","SQL","Git"}',true, now() - interval '1 day'),
  ('ios-engineer-intern-apple',(select id from public.companies where slug='apple'),'iOS Engineer Intern','Internship','On-site','Cupertino, CA','Software',9500,12000,'mo','Build delightful experiences for millions of iPhone users alongside Apple engineers.','{"Develop features in Swift/SwiftUI","Obsess over detail and performance","Partner with design"}','{"Pursuing CS degree","Swift or strong Java/Kotlin","Care about craft"}','{"Swift","SwiftUI","iOS","Git"}',false, now() - interval '5 days'),
  ('data-scientist-new-grad-microsoft',(select id from public.companies where slug='microsoft'),'Data Scientist, New Grad','New grad','Hybrid','Redmond, WA','Data & AI',125000,160000,'yr','Turn product data into insight and models that ship inside Microsoft products.','{"Build models and run experiments","Partner with product and engineering","Communicate insights clearly"}','{"BS/MS in a quantitative field","Strong Python and SQL","ML fundamentals"}','{"Python","SQL","Machine Learning","Azure"}',true, now() - interval '3 days'),
  ('swe-intern-amazon',(select id from public.companies where slug='amazon'),'SDE Intern','Internship','On-site','Seattle, WA','E-commerce',8500,11000,'mo','Own a real project end-to-end on an Amazon team and ship it during your internship.','{"Design and build a service or feature","Operate with ownership","Present your results"}','{"CS student","Strong coding fundamentals","Java, Python or C++"}','{"Java","AWS","Data Structures","Git"}',false, now() - interval '6 days'),
  ('ml-engineer-meta',(select id from public.companies where slug='meta'),'Machine Learning Engineer','Full-time','Hybrid','Menlo Park, CA','Software',160000,230000,'yr','Build ML systems powering ranking and recommendations across Meta''s apps.','{"Develop and deploy ML models in production","Run large-scale experiments","Improve model quality and efficiency"}','{"2+ years ML experience","Strong Python and ML","Experience with large datasets"}','{"Python","PyTorch","Machine Learning","Spark"}',true, now() - interval '2 days'),
  ('backend-engineer-netflix',(select id from public.companies where slug='netflix'),'Backend Engineer','Full-time','Remote','Remote (US)','Software',170000,240000,'yr','Build the resilient services that stream entertainment to the world.','{"Design high-scale backend services","Improve reliability and latency","Own systems end-to-end"}','{"3+ years backend experience","Strong systems design","Java, Kotlin or Go"}','{"Java","Microservices","AWS","Kafka"}',false, now() - interval '4 days'),
  ('ai-research-intern-nvidia',(select id from public.companies where slug='nvidia'),'AI Research Intern','Internship','On-site','Santa Clara, CA','Data & AI',10000,13000,'mo','Work with NVIDIA researchers on the frontier of deep learning and accelerated computing.','{"Prototype and evaluate models","Optimize on GPUs","Publish and present findings"}','{"Pursuing MS/PhD in ML or related","PyTorch or TensorFlow","Strong math"}','{"Python","PyTorch","CUDA","Deep Learning"}',true, now() - interval '5 days'),
  ('software-engineer-stripe',(select id from public.companies where slug='stripe'),'Software Engineer','Full-time','Hybrid','San Francisco, CA','Fintech',160000,220000,'yr','Build the APIs and systems that move money for millions of businesses.','{"Build reliable payments services","Design clean APIs","Care about correctness"}','{"2+ years experience","Strong fundamentals","Ruby, Go or TypeScript"}','{"TypeScript","Go","PostgreSQL","APIs"}',true, now() - interval '1 day'),
  ('product-design-intern-airbnb',(select id from public.companies where slug='airbnb'),'Product Design Intern','Internship','Hybrid','San Francisco, CA','Design',8000,10000,'mo','Design experiences that help guests and hosts belong anywhere.','{"Create wireframes and hi-fi designs","Contribute to the design system","Run usability tests"}','{"Design student with a portfolio","Figma proficiency","Strong eye for interaction"}','{"Figma","UI Design","Prototyping","User Research"}',false, now() - interval '7 days'),
  ('research-engineer-openai',(select id from public.companies where slug='openai'),'Research Engineer','Full-time','On-site','San Francisco, CA','Data & AI',200000,300000,'yr','Build and scale the systems behind frontier AI models.','{"Train and evaluate large models","Build research infrastructure","Collaborate with researchers"}','{"Strong engineering + ML","Python and PyTorch","Large-scale systems"}','{"Python","PyTorch","Distributed Training","CUDA"}',true, now() - interval '2 days'),
  ('new-grad-swe-openai',(select id from public.companies where slug='openai'),'Software Engineer, New Grad','New grad','On-site','San Francisco, CA','Data & AI',180000,250000,'yr','Join OpenAI early in your career and build products used by hundreds of millions.','{"Ship product and platform features","Work across the stack","Learn fast"}','{"BS/MS in CS","Strong fundamentals","Project or internship experience"}','{"Python","TypeScript","React","APIs"}',false, now() - interval '3 days'),
  ('autonomy-intern-tesla',(select id from public.companies where slug='tesla'),'Autonomy Software Intern','Internship','On-site','Austin, TX','Energy',9000,12000,'mo','Work on the software behind Tesla''s self-driving and energy products.','{"Build and test autonomy software","Work with real vehicle data","Ship improvements"}','{"CS/EE student","C++ or Python","Interest in robotics/ML"}','{"C++","Python","Robotics","Machine Learning"}',false, now() - interval '8 days'),
  ('forward-deployed-engineer-salesforce',(select id from public.companies where slug='salesforce'),'Forward Deployed Engineer','Full-time','Remote','Remote (US)','Software',140000,190000,'yr','Help enterprises get the most out of the Salesforce platform.','{"Build solutions on the platform","Work directly with customers","Translate needs into software"}','{"2+ years experience","Full-stack skills","Great communication"}','{"JavaScript","Apex","SQL","APIs"}',false, now() - interval '10 days'),
  ('data-engineer-intern-amazon',(select id from public.companies where slug='amazon'),'Data Engineer Intern','Internship','Hybrid','Seattle, WA','E-commerce',8500,11000,'mo','Build the pipelines that power Amazon analytics and ML.','{"Build and maintain ETL pipelines","Work with Spark and streaming","Improve data quality"}','{"CS/Data student","Python and SQL","Curious about distributed systems"}','{"Python","SQL","Spark","Airflow"}',false, now() - interval '4 days'),
  ('frontend-engineer-airbnb',(select id from public.companies where slug='airbnb'),'Frontend Engineer','Full-time','Hybrid','San Francisco, CA','Software',150000,205000,'yr','Build polished web experiences for the Airbnb community.','{"Ship UI in React + TypeScript","Partner with design and product","Care about performance and accessibility"}','{"2+ years frontend","React and TypeScript","Eye for detail"}','{"React","TypeScript","CSS","GraphQL"}',true, now() - interval '1 day');

insert into public.events (slug, title, host, kind, mode, location, image_url, starts_at, duration_mins, description, company_id) values
  ('stanford-tech-career-fair-2026','Stanford Tech Career Fair 2026','Stanford University','Career fair','On-site','Stanford, CA','https://picsum.photos/seed/stanfordfair/800/450', now() + interval '6 days', 360,'Meet 50+ top tech employers hiring interns and new grads. Bring your resume and your questions.', null),
  ('inside-google-engineering','Inside Google Engineering','Google','Info session','Hybrid','Mountain View + Online','https://picsum.photos/seed/googleeng/800/450', now() + interval '3 days', 90,'Engineers share what it is like to build at scale, with a live Q&A and internship walkthrough.', (select id from public.companies where slug='google')),
  ('resume-workshop-new-grads','Resume Workshop for New Grads','Spotlights','Workshop','Remote','Online','https://picsum.photos/seed/resumeus/800/450', now() + interval '2 days', 60,'A hands-on session on building a standout resume for the US tech market. Templates included.', null),
  ('berkeley-ai-night','Berkeley AI Night','UC Berkeley','Networking','On-site','Berkeley, CA','https://picsum.photos/seed/berkeleyai/800/450', now() + interval '14 days', 180,'Talks from AI researchers and engineers, plus networking with recruiters. Refreshments provided.', (select id from public.companies where slug='nvidia')),
  ('mit-fall-recruiting-expo','MIT Fall Recruiting Expo','MIT','Career fair','On-site','Cambridge, MA','https://picsum.photos/seed/mitexpo/800/450', now() + interval '20 days', 300,'Connect with startups and big tech hiring across software, data and hardware.', null),
  ('breaking-into-fintech','Breaking Into Fintech','Spotlights','Networking','Remote','Online','https://picsum.photos/seed/fintechus/800/450', now() + interval '9 days', 75,'A panel with engineers and PMs from Stripe and other fintechs on starting a fintech career.', (select id from public.companies where slug='stripe'));
